/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface account_providers_table {
  'account_id'?: string | null;
  'account_provider_id'?: string;
  'auth_provider'?: string | null;
  'auth_provider_unique_id'?: string | null;
  'created_at'?: Date;
  'updated_at'?: Date;
}
export interface accounts_table {
  'account_id'?: string;
  'active'?: boolean | null;
  'avatar_url'?: string | null;
  'city'?: string | null;
  'country'?: string | null;
  'created_at'?: Date;
  'description'?: string | null;
  'dob'?: Date | null;
  'email'?: string | null;
  'family_name'?: string | null;
  'gender'?: string | null;
  'given_name'?: string | null;
  'height'?: number | null;
  'locale'?: string | null;
  'name'?: string | null;
  'phone'?: string | null;
  'role'?: string | null;
  'ticket'?: string;
  'ticket_expiry'?: Date;
  'updated_at'?: Date;
  'weight'?: number | null;
}
export interface exercise_muscle_groups_table {
  'exercise_id'?: string | null;
  'group'?: string | null;
  'muscle_group_id'?: string | null;
}
export interface exercise_notes_table {
  'created_at'?: Date;
  'exercise_id': string;
  'exercise_note_id'?: string;
  'image'?: string | null;
  'notes'?: string | null;
  'session_id': string;
  'updated_at'?: Date;
  'video'?: string | null;
}
export interface exercises_table {
  'category'?: string | null;
  'created_at'?: Date;
  'created_by'?: string | null;
  'description'?: string | null;
  'exercise_id'?: string;
  'name'?: string | null;
  'primary_tracker'?: string | null;
  'profile'?: string | null;
  'secondary_tracker'?: string | null;
  'type'?: string | null;
  'updated_at'?: Date;
  'video'?: string | null;
  'view'?: string | null;
}
export interface muscle_groups_table {
  'description'?: string | null;
  'image'?: string | null;
  'muscle_group_id'?: string;
  'name'?: string | null;
}
export interface rest_periods_table {
  'rest_period_id'?: string;
  'seconds'?: number | null;
  'set_id'?: string | null;
}
export interface sessions_table {
  'completed'?: boolean;
  'created_at'?: Date;
  'created_by'?: string | null;
  'deload'?: boolean;
  'ended_at'?: Date | null;
  'readiness_energy'?: number | null;
  'readiness_mood'?: number | null;
  'readiness_sleep'?: number | null;
  'readiness_soreness'?: number | null;
  'readiness_stress'?: number | null;
  'session_dt'?: Date | null;
  'session_id'?: string;
  'started_at'?: Date | null;
  'updated_at'?: Date;
  'workout_id': string;
}
export interface sets_table {
  'created_at'?: Date;
  'exercise_id'?: string | null;
  'repetitions'?: number | null;
  'session_id'?: string | null;
  'set_id'?: string;
  'updated_at'?: Date;
  'weight'?: number | null;
}
export interface settings_table {
  'account_id'?: string | null;
  'appearance'?: string | null;
  'body_weight_goal'?: number | null;
  'daily_steps_goal'?: number | null;
  'setting_id'?: string;
  'unit_preference'?: string | null;
  'updated_at'?: Date;
  'weekly_cardio_minutes_goal'?: number | null;
}
export interface sleep_table {
  'account_id'?: string | null;
  'created_at'?: Date;
  'duration'?: number | null;
  'logged_at'?: Date;
  'quality'?: number | null;
  'rating'?: number | null;
  'sleep_id'?: string;
  'updated_at'?: Date;
}
export interface workout_task_exercises_table {
  'exercise_id': string;
  'repetitions'?: string | null;
  'reps_in_reserve'?: string | null;
  'rest_period'?: string | null;
  'sets'?: string | null;
  'workout_id': string;
  'workout_task_exercise_id'?: string;
  'workout_task_id': string;
}
export interface workout_tasks_table {
  'exercise_order'?: any | null;
  'workout_id': string;
  'workout_task_id'?: string;
}
export interface workouts_table {
  'category'?: string | null;
  'created_at'?: Date;
  'created_by'?: string | null;
  'description'?: string | null;
  'name'?: string | null;
  'task_order'?: any | null;
  'type'?: string | null;
  'updated_at'?: Date;
  'view'?: string | null;
  'workout_id'?: string;
}
