INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (142, 'Abductors (Hip)', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (143, 'Abdominals', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (144, 'Adductor Longus (Adductors (Hip))', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (145, 'Adductor Magnus (Adductors (Hip))', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (146, 'Adductors (Hip)', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (147, 'Anterior Delts (Delts)', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (148, 'Bicep (Elbow Flexors)', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (149, 'Biceps Brachii Long Head (Biceps)', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (150, 'Biceps Brachii Short Head (Biceps)', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (151, 'Biceps Femoris Long Head (Hamstrings)', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (152, 'Biceps Femoris Short Head (Hamstrings)', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (153, 'Brachialis (Elbow Flexors)', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (154, 'Brachioradialis (Elbow Flexors)', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (155, 'Calves (Gastrocnemius) (Lower Leg)', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (156, 'Calves (Soleus) (Lower Leg)', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (157, 'Chest (Pectoral)', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (158, 'Clavicular Pec (Chest (Pectoral))', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (159, 'Coracobrachialis', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (160, 'Costal Pec (Chest (Pectoral))', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (161, 'Delts', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (162, 'External Rotators', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (163, 'Elbow Flexors', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (164, 'Erector Spinae (Trunk & Core)', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (165, 'External Oblique (Trunk & Core)', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (166, 'Glutes', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (167, 'Gluteus Maximus (Glutes)', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (168, 'Gluteus Medius (Glutes)', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (169, 'Gluteus Minimus (Glutes)', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (170, 'Gracilis (Adductors (Hip))', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (171, 'Hamstrings', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (172, 'Iliacus', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (173, 'Infraspinatous (Upper Back)', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (174, 'Internal Oblique (Trunk & Core)', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (175, 'Lat Iliac (Lats)', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (176, 'Lat Lumbar (Lats)', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (177, 'Lat Thoracic (Lats)', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (178, 'Lats', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (179, 'Lower Leg', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (180, 'Medial Delts (Delts)', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (181, 'Pec Minor (Chest (Pectoral))', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (182, 'Posterior Delts (Delts)', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (183, 'Psoas', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (184, 'Quadriceps', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (185, 'Rectus Abdominus (Abs)', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (186, 'Rectus Femoris (Quadriceps)', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (187, 'Remedial', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (188, 'Rhomboid (Upper Back)', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (189, 'Sartorius (Quadriceps)', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (190, 'Semimembrinosus (Hamstrings)', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (191, 'Semitendinosus (Hamstrings)', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (192, 'Serratus Anterior (Trunk & Core)', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (193, 'Soleus (Lower Leg)', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (194, 'Sternal Pec (Chest (Pectoral))', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (195, 'Subscapularis (Upper Back)', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (196, 'Supraspinatous (Upper Back)', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (197, 'Teres Major (Upper Back)', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (198, 'Teres Minor (Upper Back)', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (199, 'Test Muscle Group (Tibialis Anterior)', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (200, 'TFL Tensor Fascia Latae (Abductors (Hip))', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (201, 'Tibialis Anterior (Lower Leg)', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (202, 'Total Body', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (203, 'Transverse Abdominus (Abs)', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (204, 'Trap 1 Upper Trapezius (Upper Back)', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (205, 'Trap 2 Mid Trapezius (Upper Back)', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (206, 'Trap 3 Lower Trapezius (Upper Back)', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (207, 'Triceps', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (208, 'Triceps Brachii Lateral Head (Triceps)', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (209, 'Triceps Brachii Long Head (Triceps)', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (210, 'Triceps Brachii Medial Head (Triceps)', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (211, 'Trunk & Core', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (212, 'Upper Back', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (213, 'Vastus Intermedius (Quadriceps)', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (214, 'Vastus Lateralis (Quadriceps)', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (215, 'VMO Vastus Medialis Oblique (Quadriceps)', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (216, 'Forearms', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (218, 'Forearms (extensors)', null, null);
INSERT INTO public.muscle_groups (muscle_group_id, name, description, image) VALUES (217, 'Forearms (flexors)', null, null);